name: Run Type-check & Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typecheck-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install

      - name: Run client tests & typecheck
        run: |
          cd client
          npm test
          npm run typecheck

      - name: Run server tests & typecheck
        run: |
          cd server
          npm test
          npm run typecheck
